name: spender
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  sqflite: ^2.2.2
  path_provider: ^2.0.11
  path: ^1.8.2
  flutter_bloc: ^8.1.1
  intl: ^0.18.0
  bloc: ^8.1.0
  equatable: ^2.0.5
  decimal: ^2.3.2
  fl_chart: ^0.55.2
  flutter_svg: ^1.1.6
  table_calendar: ^3.0.9
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/avatar/


  fonts:
    - family: home
      fonts:
        - asset: assets/fonts/home.ttf
    - family: card
      fonts:
        - asset: assets/fonts/card.ttf
    - family: add
      fonts:
        - asset: assets/fonts/add.ttf
    - family: whiteboard
      fonts:
        - asset: assets/fonts/whiteboard.ttf
    - family: cart
      fonts:
        - asset: assets/fonts/cart.ttf
    - family: editpen
      fonts:
        - asset: assets/fonts/editpen.ttf
    - family: Bin
      fonts:
        - asset: assets/fonts/Bin.ttf
    - family: QuillPencil
      fonts:
        - asset: assets/fonts/QuillPencil.ttf
    - family: Receipt
      fonts:
        - asset: assets/fonts/Receipt.ttf
    - family: Back
      fonts:
        - asset: assets/fonts/Back.ttf
    - family: Divider
      fonts:
        - asset: assets/fonts/Divider.ttf
    - family: Equal
      fonts:
        - asset: assets/fonts/Equal.ttf
    - family: Multiply
      fonts:
        - asset: assets/fonts/Multiply.ttf
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
        - asset: assets/fonts/WorkSans-Medium.ttf
        - asset: assets/fonts/WorkSans-Thin.ttf
        - asset: assets/fonts/WorkSans-Bold.ttf

